# Generated by Django 3.2.7 on 2021-09-07 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coin_offering', '0002_auto_20210906_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='bid',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocated_tokens', to='coin_offering.bid'),
        ),
    ]
